import { useEffect, useEffectEvent, useState } from 'react'
import type { ReactNode } from 'react'
import { Alert, AppBar, Box, Button, Card, CardContent, Container, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Divider, FormControl, FormControlLabel, FormLabel, Grid, Paper, Radio, RadioGroup, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, TextField, Toolbar, Typography } from '@mui/material'
import { ArrowBack, CloudUploadOutlined, DeleteOutlined, Logout } from '@mui/icons-material'
import { BarChart, LineChart } from '@mui/x-charts'
import { ApiError, api } from './api'
import type { Analysis, StatementDetail, StatementMetadata } from './api'
import { chartColors } from './theme'

const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 })
const dates = new Intl.DateTimeFormat('es-CL')
const formatDate = (value: string) => dates.format(new Date(`${value}T12:00:00`))
const formatMonth = (value: string) => formatDate(`${value}-01`)
const numericCell = { textAlign: 'right', whiteSpace: 'nowrap', fontVariantNumeric: 'tabular-nums' }

function TabPanel({ value, index, children }: { value: number; index: number; children: ReactNode }) {
  return <Box role="tabpanel" hidden={value !== index} id={`primary-panel-${index}`} aria-labelledby={`primary-tab-${index}`}>{value === index && children}</Box>
}

function ResponsiveTable({ label, minWidth, children }: { label: string; minWidth: number; children: ReactNode }) {
  return <TableContainer tabIndex={0} aria-label={label} sx={{ maxWidth: '100%', overflowX: 'auto', mt: 1.5 }}>
    <Table size="small" aria-label={label} sx={{ minWidth }}>
      {children}
    </Table>
  </TableContainer>
}

export default function App() {
  const [authenticated, setAuthenticated] = useState(false)
  const [tab, setTab] = useState(0)
  const [statements, setStatements] = useState<StatementMetadata[]>([])
  const [offset, setOffset] = useState(0)
  const [detail, setDetail] = useState<StatementDetail | null>(null)
  const [anchorStatementId, setAnchorStatementId] = useState<string | null>(null)
  const [analysis, setAnalysis] = useState<Analysis | null>(null)

  const clearSession = () => { setAuthenticated(false); setStatements([]); setDetail(null); setAnchorStatementId(null); setAnalysis(null) }
  const refresh = async (nextOffset = offset) => {
    try {
      const response = await api.listStatements(50, nextOffset)
      setStatements(response.statements)
      setOffset(nextOffset)
    } catch (error) {
      if (error instanceof ApiError && error.status === 401) clearSession()
      throw error
    }
  }
  const loadStatements = useEffectEvent(() => { void refresh() })
  // Synchronize the browser session with protected server state.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { if (authenticated) loadStatements() }, [authenticated])

  if (!authenticated) return <Access onAccess={() => setAuthenticated(true)} />
  return <Box sx={{ minHeight: '100vh', bgcolor: 'background.default' }}>
    <AppBar component="header" position="sticky" color="inherit" elevation={0} sx={{ borderBottom: 1, borderColor: 'divider' }}>
      <Toolbar sx={{ gap: 2 }}><Typography component="h1" variant="h4" sx={{ flexGrow: 1 }}>Zut Balance</Typography><Button startIcon={<Logout aria-hidden="true" />} onClick={() => { void api.logout().finally(clearSession) }}>Cerrar sesión</Button></Toolbar>
    </AppBar>
    <Container component="main" maxWidth="lg" sx={{ py: { xs: 2, sm: 3 } }}>
      <Box component="nav" aria-label="Secciones principales"><Tabs value={tab} onChange={(_, value) => setTab(value)} sx={{ mb: 3 }}><Tab id="primary-tab-0" aria-controls="primary-panel-0" label="Cartolas" /><Tab id="primary-tab-1" aria-controls="primary-panel-1" label="Análisis" /></Tabs></Box>
      <TabPanel value={tab} index={0}><StatementsView statements={statements} offset={offset} detail={detail} refresh={refresh} onUnauthorized={clearSession} onDetail={setDetail} onDeleted={(id) => { setDetail(null); if (anchorStatementId === id) setAnchorStatementId(null); setAnalysis(null); void refresh() }} /></TabPanel>
      <TabPanel value={tab} index={1}><AnalysisView anchorStatementId={anchorStatementId} onAnchorStatementId={setAnchorStatementId} onUnauthorized={clearSession} analysis={analysis} onAnalysis={setAnalysis} /></TabPanel>
    </Container>
  </Box>
}

function Access({ onAccess }: { onAccess: () => void }) {
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); setError('')
    try { await api.login(password); onAccess() } catch { setError('No fue posible iniciar sesión.') } finally { setBusy(false) }
  }
  return <Container component="main" maxWidth="sm" sx={{ pt: { xs: 8, md: 16 } }}><Paper component="form" onSubmit={submit} aria-busy={busy} sx={{ p: { xs: 2, sm: 4 } }}><Typography component="h1" variant="h2" gutterBottom>Tu balance, bajo control.</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Ingresa la contraseña del administrador para acceder a los datos.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<TextField label="Contraseña" type="password" value={password} onChange={(event) => setPassword(event.target.value)} required fullWidth autoFocus /><Button type="submit" variant="contained" disabled={!password || busy} sx={{ mt: 3 }} fullWidth>{busy ? 'Verificando...' : 'Iniciar sesión'}</Button></Paper></Container>
}

function StatementsView({ statements, offset, detail, refresh, onUnauthorized, onDetail, onDeleted }: { statements: StatementMetadata[]; offset: number; detail: StatementDetail | null; refresh: (offset?: number) => Promise<void>; onUnauthorized: () => void; onDetail: (detail: StatementDetail | null) => void; onDeleted: (id: string) => void }) {
  const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false); const [deleting, setDeleting] = useState(false)
  const handle = (caught: unknown, fallback: string) => { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError(caught instanceof ApiError ? caught.message : fallback) }
  const upload = async (file: File | undefined) => { if (!file || uploading) return; setUploading(true); setError(''); try { const stored = await api.uploadStatement(file); await refresh(); onDetail(stored); setMessage('La cartola está disponible para revisión.') } catch (caught) { handle(caught, 'No se pudo cargar la cartola.') } finally { setUploading(false) } }
  const open = async (id: string) => { setError(''); try { onDetail(await api.getStatement(id)) } catch (caught) { handle(caught, 'No se pudo abrir la cartola.') } }
  const remove = async () => { if (!detail) return; setDeleting(true); try { await api.deleteStatement(detail.statement_id); onDeleted(detail.statement_id); setConfirm(false); setMessage('La cartola se eliminó permanentemente.') } catch (caught) { handle(caught, 'No se pudo eliminar la cartola.') } finally { setDeleting(false) } }
  const dialog = <Dialog open={confirm} onClose={() => !deleting && setConfirm(false)}><DialogTitle>¿Eliminar cartola?</DialogTitle><DialogContent><DialogContentText>Se eliminarán permanentemente la cartola, sus movimientos y clasificaciones.</DialogContentText></DialogContent><DialogActions><Button disabled={deleting} onClick={() => setConfirm(false)}>Cancelar</Button><Button color="error" startIcon={<DeleteOutlined aria-hidden="true" />} disabled={deleting} onClick={() => void remove()}>{deleting ? 'Eliminando...' : 'Eliminar'}</Button></DialogActions></Dialog>
  if (detail) return <><StatementDetailView detail={detail} onBack={() => onDetail(null)} onDelete={() => setConfirm(true)} />{dialog}</>
  return <Stack spacing={3}><Card><CardContent sx={{ p: { xs: 2, sm: 3 }, '&:last-child': { pb: { xs: 2, sm: 3 } } }}><Typography component="h2" variant="h3">Carga una cartola</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Un PDF, hasta 10 MiB y 20 páginas.</Typography><Button component="label" startIcon={<CloudUploadOutlined aria-hidden="true" />} variant="contained" disabled={uploading} aria-busy={uploading}>{uploading ? 'Procesando...' : 'Seleccionar PDF'}<input hidden type="file" accept="application/pdf" onChange={(event) => upload(event.target.files?.[0])} /></Button></CardContent></Card>{message && <Alert severity="success">{message}</Alert>}{error && <Alert severity="error">{error}</Alert>}<Paper sx={{ p: { xs: 2, sm: 3 } }}><Typography component="h2" variant="h3">Historial</Typography>{statements.length === 0 ? <Typography color="text.secondary" sx={{ mt: 1 }}>Aún no hay cartolas cargadas.</Typography> : <Stack divider={<Divider />}>{statements.map((item) => <Grid container key={item.statement_id} sx={{ py: 1.5, alignItems: 'center' }}><Grid size={{ xs: 12, sm: 6, md: 3 }}>{formatDate(item.period_start)} a {formatDate(item.period_end)}</Grid><Grid size={{ xs: 6, md: 3 }}>{item.bank}<br /><Typography variant="body2" color="text.secondary">{item.product}</Typography></Grid><Grid size={{ xs: 6, md: 3 }}>{item.masked_account_number ?? 'No informada'}</Grid><Grid size={{ xs: 12, md: 3 }}><Button onClick={() => void open(item.statement_id)}>Ver detalle</Button></Grid></Grid>)}</Stack>}<Stack direction="row" sx={{ mt: 2, justifyContent: 'space-between' }}><Button disabled={offset === 0} onClick={() => void refresh(Math.max(0, offset - 50))}>Anterior</Button><Button disabled={statements.length < 50} onClick={() => void refresh(offset + 50)}>Siguiente</Button></Stack></Paper>{dialog}</Stack>
}

function StatementDetailView({ detail, onBack, onDelete }: { detail: StatementDetail; onBack: () => void; onDelete: () => void }) { return <Stack spacing={3}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Button startIcon={<ArrowBack aria-hidden="true" />} onClick={onBack}>Volver al historial</Button><Button color="error" startIcon={<DeleteOutlined aria-hidden="true" />} onClick={onDelete}>Eliminar</Button></Stack><Paper sx={{ p: { xs: 2, sm: 3 } }}><Typography component="h2" variant="h2">{detail.metadata.bank}</Typography><Typography color="text.secondary">{detail.metadata.product} · {detail.metadata.masked_account_number ?? 'Cuenta no informada'} · {formatDate(detail.metadata.period_start)} a {formatDate(detail.metadata.period_end)}</Typography></Paper><Paper sx={{ p: { xs: 1, sm: 2 }, minWidth: 0 }}><Typography component="h2" variant="h3" sx={{ px: { xs: 1, sm: 0 } }}>Movimientos</Typography><ResponsiveTable label="Movimientos de la cartola" minWidth={760}><TableHead><TableRow><TableCell scope="col">Fecha</TableCell><TableCell scope="col">Descripción</TableCell><TableCell scope="col">Referencia / canal</TableCell><TableCell scope="col" align="right">Monto</TableCell><TableCell scope="col">Tipo</TableCell><TableCell scope="col">Categoría</TableCell><TableCell scope="col">Comercio</TableCell></TableRow></TableHead><TableBody>{detail.transactions.map((item, index) => <TableRow key={`${item.date}-${index}`}><TableCell sx={{ whiteSpace: 'nowrap' }}>{formatDate(item.date)}</TableCell><TableCell sx={{ overflowWrap: 'anywhere', minWidth: 180 }}>{item.description}</TableCell><TableCell sx={{ overflowWrap: 'anywhere' }}>{item.document_number ?? item.branch_or_channel ?? 'No informado'}</TableCell><TableCell align="right" sx={numericCell}>{money.format(item.amount)}</TableCell><TableCell>{item.movement_type}</TableCell><TableCell>{item.classification?.category ?? 'sin categoría'}</TableCell><TableCell sx={{ overflowWrap: 'anywhere' }}>{item.classification?.merchant_name ?? 'No informado'}</TableCell></TableRow>)}</TableBody></ResponsiveTable></Paper></Stack> }

function AnalysisView({ anchorStatementId, onAnchorStatementId, onUnauthorized, analysis, onAnalysis }: { anchorStatementId: string | null; onAnchorStatementId: (value: string | null) => void; onUnauthorized: () => void; analysis: Analysis | null; onAnalysis: (value: Analysis | null) => void }) {
  const [catalog, setCatalog] = useState<StatementMetadata[]>([]); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const loadCatalog = useEffectEvent(() => { void api.listStatements(100, 0).then((response) => setCatalog(response.statements)).catch((caught: unknown) => { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError('No se pudo cargar el catálogo de cartolas.') }) })
  useEffect(() => { loadCatalog() }, [])
  const rangeValid = (!from || !to) || from <= to
  const submit = async () => { if (!anchorStatementId || !rangeValid) return; setBusy(true); setError(''); try { onAnalysis(await api.getAnalysis(anchorStatementId, from || undefined, to || undefined)) } catch (caught) { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError(caught instanceof ApiError ? caught.message : 'No se pudo calcular el análisis.') } finally { setBusy(false) } }
  return <Stack spacing={3}><Paper sx={{ p: { xs: 2, sm: 3 } }} aria-busy={busy}><Typography component="h2" variant="h2">Explora tu gasto</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Elige una cartola ancla. El análisis incorpora automáticamente su historial compatible.</Typography>{catalog.length === 0 ? <Alert severity="info">Carga una cartola para comenzar el análisis.</Alert> : <FormControl fullWidth><FormLabel id="anchor-statement-label">Cartola ancla</FormLabel><RadioGroup aria-labelledby="anchor-statement-label" name="anchor-statement" value={anchorStatementId ?? ''} onChange={(event) => { onAnchorStatementId(event.target.value); onAnalysis(null) }} sx={{ mt: 1 }}>{catalog.map((item) => <FormControlLabel key={item.statement_id} value={item.statement_id} control={<Radio />} label={<Box><Typography>{item.product}</Typography><Typography variant="body2" color="text.secondary">{item.masked_account_number ?? 'Cuenta no informada'} · {formatDate(item.period_start)} a {formatDate(item.period_end)}</Typography></Box>} sx={{ alignItems: 'flex-start', py: 0.5, m: 0 }} />)}</RadioGroup></FormControl>}<Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mt: 3 }}><TextField label="Desde" type="date" value={from} onChange={(event) => setFrom(event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField label="Hasta" type="date" value={to} onChange={(event) => setTo(event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><Button variant="contained" onClick={() => void submit()} disabled={!anchorStatementId || !rangeValid || busy}>{busy ? 'Calculando...' : 'Actualizar análisis'}</Button></Stack>{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}</Paper>{analysis && <Dashboard analysis={analysis} />}</Stack>
}

export function Dashboard({ analysis }: { analysis: Analysis }) {
  const { summary } = analysis
  const metrics = [
    ['Gasto', summary.spending_amount, summary.transaction_count],
    ['Créditos', summary.credits_amount, summary.credits_count],
    ['Débitos excluidos', summary.excluded_debits_amount, summary.excluded_debits_count],
    ['Sin categoría', summary.uncategorized_amount, summary.uncategorized_count],
  ] as const
  return <Stack spacing={3}>
    <SignalsView analysis={analysis} />
    <Paper component="section" aria-labelledby="summary-heading" sx={{ overflow: 'hidden' }}><Typography component="h2" variant="h3" id="summary-heading" sx={{ px: { xs: 2, sm: 3 }, pt: { xs: 2, sm: 3 } }}>Resumen del período</Typography><Grid container sx={{ mt: 1 }}>{metrics.map(([label, amount, count], index) => <Grid key={label} size={{ xs: 12, sm: 6, md: 3 }} sx={{ minWidth: 0, borderTop: 1, borderColor: 'divider', borderLeft: { md: index ? 1 : 0 }, borderRight: { sm: index % 2 ? 0 : 1, md: 0 }, '&:last-child': { borderRight: 0 } }}><Box sx={{ p: { xs: 2, sm: 3 } }}><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="h3" sx={{ fontVariantNumeric: 'tabular-nums', whiteSpace: 'nowrap' }}>{money.format(amount)}</Typography><Typography variant="body2" color="text.secondary">{count} movimientos</Typography></Box></Grid>)}</Grid></Paper>
    <CoverageView analysis={analysis} />
    <Grid container spacing={3}><Grid size={{ xs: 12, md: 7 }} sx={{ minWidth: 0 }}><Paper component="section" aria-labelledby="monthly-heading" sx={{ p: { xs: 1, sm: 2 }, minWidth: 0 }}><Typography component="h2" variant="h3" id="monthly-heading" sx={{ px: { xs: 1, sm: 0 } }}>Evolución mensual</Typography>{analysis.monthly.length === 0 ? <Typography color="text.secondary" sx={{ p: 1 }}>No hay evolución mensual para mostrar.</Typography> : <LineChart aria-labelledby="monthly-heading" height={280} colors={[chartColors[0]]} xAxis={[{ data: analysis.monthly.map((item) => formatMonth(item.month)), scaleType: 'point' }]} series={[{ data: analysis.monthly.map((item) => item.amount), label: 'Gasto CLP', valueFormatter: (value) => money.format(value ?? 0) }]} />}</Paper></Grid><Grid size={{ xs: 12, md: 5 }} sx={{ minWidth: 0 }}><Paper component="section" aria-labelledby="categories-heading" sx={{ p: { xs: 1, sm: 2 }, minWidth: 0 }}><Typography component="h2" variant="h3" id="categories-heading" sx={{ px: { xs: 1, sm: 0 } }}>Categorías</Typography>{summary.by_category.length === 0 ? <Typography color="text.secondary" sx={{ p: 1 }}>No hay gasto categorizado para mostrar.</Typography> : <><BarChart aria-labelledby="categories-heading" height={280} colors={chartColors} xAxis={[{ data: summary.by_category.map((item) => item.category), scaleType: 'band' }]} series={[{ data: summary.by_category.map((item) => item.amount), label: 'CLP', valueFormatter: (value) => money.format(value ?? 0) }]} /><ResponsiveTable label="Desglose de gasto por categoría" minWidth={420}><TableHead><TableRow><TableCell scope="col">Categoría</TableCell><TableCell scope="col" align="right">Monto</TableCell><TableCell scope="col" align="right">Movimientos</TableCell></TableRow></TableHead><TableBody>{summary.by_category.map((category) => <TableRow key={category.category}><TableCell sx={{ overflowWrap: 'anywhere' }}>{category.category}</TableCell><TableCell align="right" sx={numericCell}>{money.format(category.amount)}</TableCell><TableCell align="right" sx={numericCell}>{category.count}</TableCell></TableRow>)}</TableBody></ResponsiveTable></>}</Paper></Grid></Grid>
    <Paper component="section" aria-labelledby="monthly-detail-heading" sx={{ p: { xs: 1, sm: 2 }, minWidth: 0 }}><Typography component="h2" variant="h3" id="monthly-detail-heading" sx={{ px: { xs: 1, sm: 0 } }}>Detalle mensual</Typography><ResponsiveTable label="Detalle de gasto mensual" minWidth={620}><TableHead><TableRow><TableCell scope="col">Mes</TableCell><TableCell scope="col" align="right">Gasto</TableCell><TableCell scope="col" align="right">Movimientos</TableCell><TableCell scope="col" align="right">Cambio absoluto</TableCell><TableCell scope="col" align="right">Variación</TableCell></TableRow></TableHead><TableBody>{analysis.monthly.map((item) => <TableRow key={item.month}><TableCell sx={{ whiteSpace: 'nowrap' }}>{formatMonth(item.month)}</TableCell><TableCell align="right" sx={numericCell}>{money.format(item.amount)}</TableCell><TableCell align="right" sx={numericCell}>{item.count}</TableCell><TableCell align="right" sx={numericCell}>{item.absolute_change === null ? 'No disponible' : money.format(item.absolute_change)}</TableCell><TableCell align="right" sx={numericCell}>{item.percentage_change === null ? 'No disponible' : `${item.percentage_change}%`}</TableCell></TableRow>)}</TableBody></ResponsiveTable></Paper>
    <Grid container spacing={3}><Grid size={{ xs: 12, md: 6 }} sx={{ minWidth: 0 }}><MerchantView merchants={analysis.top_merchants} /></Grid><Grid size={{ xs: 12, md: 6 }} sx={{ minWidth: 0 }}><RecurrenceView candidates={analysis.recurrence_candidates} /></Grid></Grid>
  </Stack>
}

function SignalsView({ analysis }: { analysis: Analysis }) { const highlight = analysis.highlights.largest_monthly_change; return <Paper component="section" aria-labelledby="signals-heading" sx={{ p: { xs: 2, sm: 3 } }}><Typography component="h2" variant="h3" id="signals-heading" gutterBottom>Avisos y destacados</Typography>{analysis.notices.length === 0 && !highlight && <Typography color="text.secondary">No hay avisos ni variaciones destacadas para este período.</Typography>}<Stack spacing={2}>{analysis.notices.map((notice) => notice.kind === 'incomplete_coverage' ? <Alert key={notice.kind} severity={notice.severity}><Typography variant="subtitle2">Cobertura incompleta</Typography>{notice.gaps.map((gap) => <Typography key={`${gap.from}-${gap.to}`} variant="body2">Hueco: {formatDate(gap.from)} a {formatDate(gap.to)}</Typography>)}{notice.partial_months.length > 0 && <Typography variant="body2">Meses parciales: {notice.partial_months.join(', ')}.</Typography>}</Alert> : <Alert key={notice.kind} severity={notice.severity}><Typography variant="subtitle2">Clasificación limitada</Typography><Typography variant="body2">Sin categoría: {money.format(notice.uncategorized_amount)} ({notice.uncategorized_count} movimientos).</Typography><Typography variant="body2">Sin comercio identificado: {money.format(notice.unidentified_merchant_amount)} ({notice.unidentified_merchant_count} movimientos).</Typography>{notice.ruleset_versions.length > 1 && <Typography variant="body2">Versiones de reglas: {notice.ruleset_versions.join(', ')}.</Typography>}</Alert>)}{highlight && <Alert severity="info"><Typography variant="subtitle2">Mayor variación mensual</Typography><Typography variant="body2">{formatMonth(highlight.previous_month)} a {formatMonth(highlight.current_month)}: {money.format(highlight.absolute_change)} ({highlight.percentage_change === null ? 'sin porcentaje comparable' : `${highlight.percentage_change}%`}).</Typography></Alert>}</Stack></Paper> }

function CoverageView({ analysis }: { analysis: Analysis }) { const { coverage, summary } = analysis; return <Paper component="section" aria-labelledby="coverage-heading" sx={{ p: { xs: 2, sm: 3 } }}><Typography component="h2" variant="h3" id="coverage-heading">Cobertura y clasificación</Typography><Grid container spacing={3} sx={{ mt: 0.5 }}><Grid size={{ xs: 12, md: 6 }}><Typography variant="subtitle2" sx={{ mt: 1 }}>Cobertura temporal</Typography><Typography variant="body2" color="text.secondary">Rangos cubiertos</Typography>{coverage.covered_ranges.length ? coverage.covered_ranges.map((range) => <Typography key={`${range.from}-${range.to}`}>{formatDate(range.from)} a {formatDate(range.to)}</Typography>) : <Typography color="text.secondary">No hay rangos cubiertos.</Typography>}<Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>Huecos</Typography>{coverage.gaps.length ? coverage.gaps.map((range) => <Typography key={`${range.from}-${range.to}`}>{formatDate(range.from)} a {formatDate(range.to)}</Typography>) : <Typography color="text.secondary">No hay huecos informados.</Typography>}{coverage.partial_months.length > 0 && <Alert severity="warning" sx={{ mt: 2 }}>Meses con cobertura parcial: {coverage.partial_months.join(', ')}.</Alert>}</Grid><Grid size={{ xs: 12, md: 6 }}><Typography variant="subtitle2" sx={{ mt: 1 }}>Cobertura de clasificación</Typography><Typography>Gasto de consumo: {money.format(summary.spending_amount)} ({summary.transaction_count} movimientos)</Typography><Typography>Sin categoría: {money.format(summary.uncategorized_amount)} ({summary.uncategorized_count} movimientos)</Typography><Typography sx={{ mt: 1 }}>Comercios identificados: {money.format(summary.merchant_coverage.identified_amount)} ({summary.merchant_coverage.identified_count} movimientos)</Typography><Typography>Sin comercio identificado: {money.format(summary.merchant_coverage.unidentified_amount)} ({summary.merchant_coverage.unidentified_count} movimientos)</Typography></Grid></Grid></Paper> }

function MerchantView({ merchants }: { merchants: Analysis['top_merchants'] }) { return <Paper component="section" aria-labelledby="merchants-heading" sx={{ p: { xs: 1, sm: 2 }, height: '100%', minWidth: 0 }}><Box sx={{ px: { xs: 1, sm: 0 } }}><Typography component="h2" variant="h3" id="merchants-heading">Comercios principales</Typography><Typography variant="body2" color="text.secondary">Solo considera comercios identificados.</Typography></Box>{merchants.length ? <ResponsiveTable label="Comercios principales del período" minWidth={420}><TableHead><TableRow><TableCell scope="col">Comercio</TableCell><TableCell scope="col" align="right">Monto</TableCell><TableCell scope="col" align="right">Movimientos</TableCell></TableRow></TableHead><TableBody>{merchants.map((merchant, index) => <TableRow key={`${merchant.merchant_name}-${index}`}><TableCell sx={{ overflowWrap: 'anywhere', minWidth: 170 }}>{merchant.merchant_name ?? 'No informado'}</TableCell><TableCell align="right" sx={numericCell}>{money.format(merchant.amount)}</TableCell><TableCell align="right" sx={numericCell}>{merchant.count}</TableCell></TableRow>)}</TableBody></ResponsiveTable> : <Typography color="text.secondary" sx={{ mt: 2, px: { xs: 1, sm: 0 } }}>No hay comercios identificados para mostrar.</Typography>}</Paper> }

function RecurrenceView({ candidates }: { candidates: Analysis['recurrence_candidates'] }) { return <Paper component="section" aria-labelledby="recurrence-heading" sx={{ p: { xs: 2, sm: 3 }, height: '100%', minWidth: 0 }}><Typography component="h2" variant="h3" id="recurrence-heading">Candidatos de recurrencia</Typography>{candidates.length ? <Stack spacing={2} sx={{ mt: 1 }}>{candidates.map((candidate, index) => <Box key={`${candidate.merchant_name}-${index}`} sx={{ overflowWrap: 'anywhere' }}><Typography sx={{ fontWeight: 600 }}>{candidate.merchant_name ?? 'Comercio no informado'} · {candidate.cadence}</Typography><Typography variant="body2">{candidate.count} ocurrencias entre {formatDate(candidate.dates[0])} y {formatDate(candidate.dates.at(-1) ?? candidate.dates[0])}.</Typography><Typography variant="body2">Mínimo {money.format(candidate.minimum_amount)} · promedio {money.format(candidate.average_amount)} · máximo {money.format(candidate.maximum_amount)}</Typography><Typography variant="caption">Candidato basado en fechas observadas; no confirma una suscripción.</Typography></Box>)}</Stack> : <Typography color="text.secondary" sx={{ mt: 2 }}>No hay candidatos de recurrencia para mostrar.</Typography>}</Paper> }
