import { useEffect, useEffectEvent, useState } from 'react'
import { Alert, AppBar, Box, Button, Card, CardContent, Container, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Divider, FormControlLabel, Grid, Paper, Stack, Tab, Tabs, TextField, Toolbar, Typography } from '@mui/material'
import { BarChart, LineChart } from '@mui/x-charts'
import { ApiError, api } from './api'
import type { Analysis, StatementDetail, StatementMetadata } from './api'

const money = new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 })
const dateFormat = new Intl.DateTimeFormat('es-CL')
const formatDate = (value: string) => dateFormat.format(new Date(`${value}T12:00:00`))

function App() {
  const [apiKey, setApiKey] = useState<string | null>(null)
  const [tab, setTab] = useState(0)
  const [statements, setStatements] = useState<StatementMetadata[]>([])
  const [offset, setOffset] = useState(0)
  const [detail, setDetail] = useState<StatementDetail | null>(null)
  const [selected, setSelected] = useState<string[]>([])
  const [analysis, setAnalysis] = useState<Analysis | null>(null)

  const clearSession = () => { setApiKey(null); setStatements([]); setDetail(null); setSelected([]); setAnalysis(null) }
  const handleError = (error: unknown) => { if (error instanceof ApiError && error.status === 401) clearSession() }
  const refresh = async (key = apiKey, nextOffset = offset) => {
    if (!key) return
    try { setStatements((await api.listStatements(key, 50, nextOffset)).statements); setOffset(nextOffset) } catch (error) { handleError(error); throw error }
  }
  const loadInitialStatements = useEffectEvent(() => { void refresh() })
  // Synchronize the authenticated view with server state after the key changes.
  // oxlint-disable-next-line react/set-state-in-effect
  useEffect(() => { loadInitialStatements() }, [apiKey])
  if (!apiKey) return <Access onAccess={setApiKey} />

  return <Box sx={{ minHeight: '100vh', bgcolor: '#f6f7f5' }}>
    <AppBar position="sticky" color="inherit" elevation={0}><Toolbar><Typography variant="h6" sx={{ flexGrow: 1, fontWeight: 700 }}>Zut Balance</Typography><Button onClick={clearSession}>Cerrar sesión</Button></Toolbar></AppBar>
    <Container maxWidth="lg" sx={{ py: 3 }}>
      <Tabs value={tab} onChange={(_, value) => setTab(value)} aria-label="Secciones principales" sx={{ mb: 3 }}><Tab label="Cartolas" /><Tab label="Análisis" /></Tabs>
      {tab === 0 && <StatementsView apiKey={apiKey} statements={statements} offset={offset} detail={detail} refresh={refresh} onUnauthorized={clearSession} onDetail={setDetail} onDeleted={(id) => { setDetail(null); setSelected((current) => current.filter((value) => value !== id)); setAnalysis(null); void refresh() }} />}
      {tab === 1 && <AnalysisView apiKey={apiKey} statements={statements} selected={selected} onSelected={setSelected} onUnauthorized={clearSession} analysis={analysis} onAnalysis={setAnalysis} />}
    </Container>
  </Box>
}

function Access({ onAccess }: { onAccess: (key: string) => void }) {
  const [key, setKey] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api.listStatements(key, 1, 0); onAccess(key) } catch { setError('La clave no permitió acceder a los datos.') } finally { setBusy(false) } }
  return <Container maxWidth="sm" sx={{ pt: { xs: 10, md: 18 } }}><Paper component="form" onSubmit={submit} sx={{ p: 4 }}><Typography variant="overline" color="primary">Uso local</Typography><Typography variant="h3" gutterBottom>Tu balance, bajo control.</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>La clave se usa solo durante esta sesión y se elimina al recargar la página.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<TextField label="API key" type="password" value={key} onChange={(event) => setKey(event.target.value)} required fullWidth autoFocus /><Button type="submit" variant="contained" disabled={!key || busy} sx={{ mt: 3 }} fullWidth>{busy ? 'Verificando...' : 'Acceder'}</Button></Paper></Container>
}

function StatementsView({ apiKey, statements, offset, detail, refresh, onUnauthorized, onDetail, onDeleted }: { apiKey: string; statements: StatementMetadata[]; offset: number; detail: StatementDetail | null; refresh: (key?: string, nextOffset?: number) => Promise<void>; onUnauthorized: () => void; onDetail: (detail: StatementDetail | null) => void; onDeleted: (id: string) => void }) {
  const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [confirm, setConfirm] = useState(false)
  const upload = async (file: File | undefined) => { if (!file || uploading) return; setUploading(true); setError(''); try { const stored = await api.uploadStatement(apiKey, file); await refresh(); onDetail(stored); setMessage('La cartola está disponible para revisión.') } catch (caught) { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError(caught instanceof ApiError ? caught.message : 'No se pudo cargar la cartola.') } finally { setUploading(false) } }
  const open = async (id: string) => { setError(''); try { onDetail(await api.getStatement(apiKey, id)) } catch (caught) { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError(caught instanceof ApiError ? caught.message : 'No se pudo abrir la cartola.') } }
  const remove = async () => { if (!detail) return; try { await api.deleteStatement(apiKey, detail.statement_id); onDeleted(detail.statement_id); setConfirm(false); setMessage('La cartola se eliminó permanentemente.') } catch (caught) { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError(caught instanceof ApiError ? caught.message : 'No se pudo eliminar la cartola.') } }
  if (detail) return <><StatementDetailView detail={detail} onBack={() => onDetail(null)} onDelete={() => setConfirm(true)} /><Dialog open={confirm} onClose={() => setConfirm(false)}><DialogTitle>¿Eliminar cartola?</DialogTitle><DialogContent><DialogContentText>Se eliminarán permanentemente la cartola, sus movimientos y clasificaciones.</DialogContentText></DialogContent><DialogActions><Button onClick={() => setConfirm(false)}>Cancelar</Button><Button color="error" onClick={() => void remove()}>Eliminar</Button></DialogActions></Dialog></>
  return <Stack spacing={3}><Card><CardContent><Typography variant="h5">Carga una cartola</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Un PDF, hasta 10 MiB y 20 páginas.</Typography><Button component="label" variant="contained" disabled={uploading}>{uploading ? 'Procesando...' : 'Seleccionar PDF'}<input hidden type="file" accept="application/pdf" onChange={(event) => upload(event.target.files?.[0])} /></Button></CardContent></Card>{message && <Alert severity="success">{message}</Alert>}{error && <Alert severity="error">{error}</Alert>}<Paper sx={{ p: 2 }}><Typography variant="h5" sx={{ mb: 2 }}>Historial</Typography>{statements.length === 0 ? <Typography color="text.secondary">Aún no hay cartolas cargadas.</Typography> : <Stack divider={<Divider />}><Grid container sx={{ fontWeight: 700, px: 1 }}><Grid size={{ xs: 6, md: 3 }}>Período</Grid><Grid size={{ xs: 6, md: 3 }}>Producto</Grid><Grid size={{ xs: 6, md: 3 }}>Cuenta</Grid><Grid size={{ xs: 6, md: 3 }}> </Grid></Grid>{statements.map((item) => <Grid container key={item.statement_id} sx={{ py: 1, px: 1, alignItems: 'center' }}><Grid size={{ xs: 6, md: 3 }}>{formatDate(item.period_start)} - {formatDate(item.period_end)}</Grid><Grid size={{ xs: 6, md: 3 }}>{item.bank}<br /><Typography variant="caption">{item.product}</Typography></Grid><Grid size={{ xs: 6, md: 3 }}>{item.masked_account_number ?? 'No informada'}</Grid><Grid size={{ xs: 6, md: 3 }}><Button onClick={() => void open(item.statement_id)}>Ver detalle</Button></Grid></Grid>)}</Stack>}<Stack direction="row" sx={{ mt: 2, justifyContent: 'space-between' }}><Button disabled={offset === 0} onClick={() => void refresh(apiKey, Math.max(0, offset - 50))}>Anterior</Button><Button disabled={statements.length < 50} onClick={() => void refresh(apiKey, offset + 50)}>Siguiente</Button></Stack></Paper><Dialog open={confirm} onClose={() => setConfirm(false)}><DialogTitle>¿Eliminar cartola?</DialogTitle><DialogContent><DialogContentText>Se eliminarán permanentemente la cartola, sus movimientos y clasificaciones.</DialogContentText></DialogContent><DialogActions><Button onClick={() => setConfirm(false)}>Cancelar</Button><Button color="error" onClick={() => void remove()}>Eliminar</Button></DialogActions></Dialog></Stack>
}

function StatementDetailView({ detail, onBack, onDelete }: { detail: StatementDetail; onBack: () => void; onDelete: () => void }) {
  return <Stack spacing={3}><Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}><Button onClick={onBack}>Volver al historial</Button><Button color="error" onClick={onDelete}>Eliminar</Button></Stack><Paper sx={{ p: 3 }}><Typography variant="h4">{detail.metadata.bank}</Typography><Typography color="text.secondary">{detail.metadata.product} · {detail.metadata.masked_account_number ?? 'Cuenta no informada'} · {formatDate(detail.metadata.period_start)} a {formatDate(detail.metadata.period_end)}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={3} sx={{ mt: 3 }}><Metric label="Saldo inicial" value={detail.summary.opening_balance} /><Metric label="Saldo final" value={detail.summary.closing_balance} /><Metric label="Disponible" value={detail.summary.available_balance} /></Stack></Paper><Paper sx={{ p: 2, overflowX: 'auto' }}><Typography variant="h5" sx={{ mb: 2 }}>Movimientos</Typography><Box component="table" className="data-table"><thead><tr><th>Fecha</th><th>Descripción</th><th>Referencia / canal</th><th>Monto</th><th>Tipo</th><th>Categoría</th><th>Comercio</th></tr></thead><tbody>{detail.transactions.map((item, index) => <tr key={`${item.date}-${index}`}><td>{formatDate(item.date)}</td><td>{item.description}</td><td>{item.document_number ?? item.branch_or_channel ?? '—'}</td><td>{money.format(item.amount)}</td><td>{item.movement_type}</td><td>{item.classification?.category ?? 'sin categoría'}</td><td>{item.classification?.merchant_name ?? '—'}</td></tr>)}</tbody></Box></Paper></Stack>
}

function AnalysisView({ apiKey, statements, selected, onSelected, onUnauthorized, analysis, onAnalysis }: { apiKey: string; statements: StatementMetadata[]; selected: string[]; onSelected: (values: string[]) => void; onUnauthorized: () => void; analysis: Analysis | null; onAnalysis: (value: Analysis | null) => void }) {
  const [catalog, setCatalog] = useState(statements); const selectedStatements = catalog.filter((item) => selected.includes(item.statement_id)); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const loadCatalog = useEffectEvent(() => { void api.listStatements(apiKey, 100, 0).then((response) => setCatalog(response.statements)).catch((caught: unknown) => { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError('No se pudo cargar el catálogo de cartolas.') }) })
  useEffect(() => { loadCatalog() }, [apiKey])
  const compatibility = selectedStatements.length < 2 || selectedStatements.every((item) => `${item.bank}|${item.product}|${item.currency}|${item.masked_account_number}` === `${selectedStatements[0].bank}|${selectedStatements[0].product}|${selectedStatements[0].currency}|${selectedStatements[0].masked_account_number}`)
  const periods = [...selectedStatements].sort((left, right) => left.period_start.localeCompare(right.period_start))
  const overlapping = periods.some((item, index) => index > 0 && item.period_start <= periods[index - 1].period_end)
  const rangeValid = (() => { if (!from || !to || from > to) return false; const maximum = new Date(`${from}T12:00:00`); maximum.setMonth(maximum.getMonth() + 24); maximum.setDate(maximum.getDate() - 1); return new Date(`${to}T12:00:00`) <= maximum })()
  const toggle = (item: StatementMetadata) => { const next = selected.includes(item.statement_id) ? selected.filter((id) => id !== item.statement_id) : [...selected, item.statement_id]; if (next.length > 100) return; onSelected(next); const values = catalog.filter((value) => next.includes(value.statement_id)); if (values.length) { setFrom(values.map((value) => value.period_start).sort()[0]); setTo(values.map((value) => value.period_end).sort().at(-1) ?? '') }; onAnalysis(null) }
  const submit = async () => { if (!selected.length || !rangeValid || !compatibility || overlapping) return; setBusy(true); setError(''); try { onAnalysis(await api.getAnalysis(apiKey, selected, from, to)) } catch (caught) { if (caught instanceof ApiError && caught.status === 401) onUnauthorized(); else setError(caught instanceof ApiError ? caught.message : 'No se pudo calcular el análisis.') } finally { setBusy(false) } }
  return <Stack spacing={3}><Paper sx={{ p: 3 }}><Typography variant="h4">Explora tu gasto</Typography><Typography color="text.secondary" sx={{ mb: 2 }}>Selecciona cartolas compatibles. El backend confirmará cobertura y solapamientos.</Typography>{catalog.length === 0 ? <Alert severity="info">Carga una cartola para comenzar el análisis.</Alert> : <Stack spacing={1}>{catalog.map((item) => <FormControlLabel key={item.statement_id} control={<input type="checkbox" checked={selected.includes(item.statement_id)} onChange={() => toggle(item)} />} label={`${item.product} · ${item.masked_account_number ?? 'cuenta no informada'} · ${item.period_start} a ${item.period_end}`} />)}</Stack>}{!compatibility && <Alert severity="warning" sx={{ mt: 2 }}>Las cartolas elegidas no parecen compatibles.</Alert>}{overlapping && <Alert severity="warning" sx={{ mt: 2 }}>Los períodos de las cartolas elegidas se solapan.</Alert>}<Stack direction={{ xs: 'column', sm: 'row' }} spacing={2} sx={{ mt: 3 }}><TextField label="Desde" type="date" value={from} onChange={(event) => setFrom(event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField label="Hasta" type="date" value={to} onChange={(event) => setTo(event.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><Button variant="contained" onClick={() => void submit()} disabled={!selected.length || !rangeValid || !compatibility || overlapping || busy}>{busy ? 'Calculando...' : 'Actualizar análisis'}</Button></Stack>{!rangeValid && (from || to) && <Alert severity="warning" sx={{ mt: 2 }}>El rango debe ser válido y no superar 24 meses.</Alert>}{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}</Paper>{analysis && <Dashboard analysis={analysis} />}</Stack>
}

function Dashboard({ analysis }: { analysis: Analysis }) { const { summary } = analysis; return <Stack spacing={3}><Grid container spacing={2}><MetricCard label="Gasto" value={money.format(summary.spending_amount)} /><MetricCard label="Créditos" value={money.format(summary.credits_amount)} /><MetricCard label="Sin categoría" value={money.format(summary.uncategorized_amount)} /></Grid>{analysis.coverage.partial_months.length > 0 && <Alert severity="warning">Cobertura parcial: {analysis.coverage.partial_months.join(', ')}.</Alert>}<Grid container spacing={3}><Grid size={{ xs: 12, md: 7 }}><Paper sx={{ p: 2 }}><Typography variant="h6">Evolución mensual</Typography><LineChart height={280} xAxis={[{ data: analysis.monthly.map((item) => item.month), scaleType: 'point' }]} series={[{ data: analysis.monthly.map((item) => item.amount), label: 'Gasto CLP' }]} /></Paper></Grid><Grid size={{ xs: 12, md: 5 }}><Paper sx={{ p: 2 }}><Typography variant="h6">Categorías</Typography><BarChart height={280} xAxis={[{ data: summary.by_category.map((item) => item.category), scaleType: 'band' }]} series={[{ data: summary.by_category.map((item) => item.amount), label: 'CLP' }]} /></Paper></Grid></Grid><Paper sx={{ p: 2 }}><Typography variant="h6">Detalle mensual</Typography><Box component="table" className="data-table"><thead><tr><th>Mes</th><th>Gasto</th><th>Movimientos</th><th>Variación</th></tr></thead><tbody>{analysis.monthly.map((item) => <tr key={item.month}><td>{item.month}</td><td>{money.format(item.amount)}</td><td>{item.count}</td><td>{item.percentage_change === null ? 'No disponible' : `${item.percentage_change}%`}</td></tr>)}</tbody></Box></Paper><Grid container spacing={3}><Grid size={{ xs: 12, md: 6 }}><Paper sx={{ p: 2 }}><Typography variant="h6">Comercios principales</Typography>{analysis.top_merchants.length ? analysis.top_merchants.map((item) => <Typography key={item.merchant_name}>{item.merchant_name}: {money.format(item.amount)} · {item.count} movimientos</Typography>) : <Typography color="text.secondary">No hay comercios identificados.</Typography>}</Paper></Grid><Grid size={{ xs: 12, md: 6 }}><Paper sx={{ p: 2 }}><Typography variant="h6">Candidatos recurrentes</Typography>{analysis.recurrence_candidates.length ? analysis.recurrence_candidates.map((item) => <Typography key={item.merchant_name}>{item.merchant_name}: {item.cadence} · promedio {money.format(item.average_amount)}</Typography>) : <Typography color="text.secondary">No hay candidatos recurrentes.</Typography>}</Paper></Grid></Grid></Stack> }

function Metric({ label, value }: { label: string; value: number | null }) { return <Box><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6">{value === null ? '—' : money.format(value)}</Typography></Box> }
function MetricCard({ label, value }: { label: string; value: string }) { return <Grid size={{ xs: 12, sm: 4 }}><Paper sx={{ p: 2 }}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5">{value}</Typography></Paper></Grid> }

export default App
